version: 2
registries:
  maven-central:
    type: maven-repository
    url: https://repo.maven.apache.org/maven2
  gradle-plugin-portal:
    type: maven-repository
    url: https://plugins.gradle.org/m2
  google:
    type: maven-repository
    url: https://dl.google.com/dl/android/maven2
updates:
  - package-ecosystem: "gradle"
    registries: "*"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "org.eclipse.jgit:org.eclipse.jgit" # because of min Java version
        update-types: [ "version-update:semver-major" ]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
