[versions]
kotlin = "1.7.20"
junit = "5.9.2"

[libraries]
jgit = "org.eclipse.jgit:org.eclipse.jgit:5.13.1.202206130422-r"
junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-params = { module = "org.junit.jupiter:junit-jupiter-params", version = "junit" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

[plugins]
android = "com.android.application:7.4.0"
buildConfig = "com.github.gmazzo.buildconfig:3.1.0"
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "kotlin" }
gitVersioning = { id = "me.qoomon.git-versioning", version = "6.4.2" }
gradle-pluginPublish = { id = "com.gradle.plugin-publish", version = "1.2.0" }
gradle-nexusPublish = { id = "io.github.gradle-nexus.publish-plugin", version = "1.1.0" }
