[versions]
kotlin = "1.8.22"

[libraries]
jgit = "org.eclipse.jgit:org.eclipse.jgit:6.6.0.202305301015-r"
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

[plugins]
android = "com.android.application:8.0.2"
buildConfig = "com.github.gmazzo.buildconfig:4.1.1"
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-samWithReceiver = { id = "org.jetbrains.kotlin.plugin.sam.with.receiver", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version = "1.8.20" }
gradle-pluginPublish = { id = "com.gradle.plugin-publish", version = "1.2.0" }
gradle-nexusPublish = { id = "io.github.gradle-nexus.publish-plugin", version = "1.3.0" }
