[versions]
kotlin = "1.8.20"

[libraries]
jgit = "org.eclipse.jgit:org.eclipse.jgit:5.13.1.202206130422-r"
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

[plugins]
android = "com.android.application:7.4.0"
buildConfig = "com.github.gmazzo.buildconfig:4.0.1"
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version = "1.8.10" }
gitVersioning = { id = "me.qoomon.git-versioning", version = "6.4.2" }
gradle-pluginPublish = { id = "com.gradle.plugin-publish", version = "1.2.0" }
gradle-nexusPublish = { id = "io.github.gradle-nexus.publish-plugin", version = "1.3.0" }
