[versions]
kotlin = "1.7.21"
junit = "5.9.1"

[libraries]
jgit = "org.eclipse.jgit:org.eclipse.jgit:6.4.0.202211300538-r"
junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-params = { module = "org.junit.jupiter:junit-jupiter-params", version = "junit" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
