[versions]
kotlin = "1.9.21"

[libraries]
jgit = "org.eclipse.jgit:org.eclipse.jgit:6.7.0.202309050840-r"
junit-bom = "org.junit:junit-bom:5.8.1"
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

[plugins]
android = "com.android.application:8.2.0"
buildConfig = "com.github.gmazzo.buildconfig:4.2.0"
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-samWithReceiver = { id = "org.jetbrains.kotlin.plugin.sam.with.receiver", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version = "1.9.10" }
gradle-pluginPublish = { id = "com.gradle.plugin-publish", version = "1.2.1" }
gradle-nexusPublish = { id = "io.github.gradle-nexus.publish-plugin", version = "1.3.0" }
