name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Host setup
        uses: ./.github/actions/host-setup
      - name: Test & Build
        run: ./gradlew -s build
      - name: Coverage report
        uses: codecov/codecov-action@v3
